category = {
    'select a category': 'SELECT A CATEGORY',
    'antiques': 'ANTIQUES',
    'books': 'BOOKS',
    'cameras': 'CAMERAS',
    'collectibles': 'COLLECTIBLES',
    'dolls': 'DOLLS',
    'electronics': 'ELECTRONICS',
    'flatware': 'FLATWARE',
    'furniture': 'FURNITURE',
    'games': 'GAMES',
    'glassware': 'GLASSWARE',
    'household items': 'HOUSEHOLD ITEMS',
    'jewelry': 'JEWELRY',
    'knick knacks': 'KNICK KNACKS',
    'mens fashion': 'MENS FASHION',
    'miscellaneous': 'MISCELLANEOUS',
    'movies - dvd': 'MOVIES - DVD',
    'movies - vhs': 'MOVIES - VHS',
    'music - all': 'MUSIC - ALL',
    'music - cd': 'MUSIC - CD',
    'music - vinyl': 'MUSIC - VINYL',
    'novely items': 'NOVELTY ITEMS',
    'posters': 'POSTERS',
    'shoes': 'SHOES',
    'tools - all': 'TOOLS - ALL',
    'tools - hand tools': 'TOOLS - HAND TOOLS',
    'tools - power tools': 'TOOLS - POWER TOOLS',
    'tools - yard tools': 'TOOLS - YARD TOOLS',
    'womens fashion': 'WOMENS FASHION',
    'writing utensils': 'WRITING UTENSILS',
}

badge = {
    'none': 'NONE',
    'special': 'SPECIAL',
}
