# Generated by Django 2.2.6 on 2019-10-31 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seller_photo', models.ImageField(default=False, upload_to='media/%Y%/m%/%d')),
                ('description', models.TextField()),
                ('is_seller_of_month', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('items_listed', models.TextField(blank=True)),
            ],
        ),
    ]
