# Generated by Django 2.2.7 on 2019-11-07 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seller_address_1', models.CharField(max_length=100)),
                ('seller_address_2', models.CharField(blank=True, max_length=100)),
                ('seller_city', models.CharField(max_length=100)),
                ('seller_state', models.CharField(max_length=20)),
                ('seller_zipcode', models.CharField(max_length=10)),
                ('seller_email', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_photo', models.ImageField(default=False, upload_to='media/%Y%/m%/%d')),
                ('description', models.TextField()),
                ('is_seller_of_month', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('items_listed', models.TextField(blank=True)),
                ('item_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
