# Generated by Django 2.2.6 on 2019-10-31 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='item_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
