# Generated by Django 2.2.7 on 2019-11-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='date_joined',
            new_name='dateJoined',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='is_seller_of_month',
            new_name='isSellerOfMonth',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='item_added',
            new_name='itemAdded',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='items_listed',
            new_name='itemsListed',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_address_1',
            new_name='sellerAddress1',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_address_2',
            new_name='sellerAddress2',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_city',
            new_name='sellerCity',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_email',
            new_name='sellerEmail',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_phone',
            new_name='sellerPhone',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_photo',
            new_name='sellerPhoto',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_state',
            new_name='sellerState',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_zipcode',
            new_name='sellerZipcode',
        ),
    ]
