# Generated by Django 2.2.7 on 2019-11-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20191107_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='dateJoined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='isSellerOfMonth',
            new_name='is_seller_of_month',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='itemAdded',
            new_name='item_added',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='itemsListed',
            new_name='items_listed',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerAddress1',
            new_name='seller_address_1',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerAddress2',
            new_name='seller_address_2',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerCity',
            new_name='seller_city',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerEmail',
            new_name='seller_email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerPhone',
            new_name='seller_phone',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerPhoto',
            new_name='seller_photo',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerState',
            new_name='seller_state',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerZipcode',
            new_name='seller_zipcode',
        ),
    ]
