# Generated by Django 2.2.6 on 2019-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20191101_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_zipcode',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_state',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
