# Generated by Django 2.2.6 on 2019-11-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20191101_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_address_1',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_address_2',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
