# Generated by Django 2.2.6 on 2019-11-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_auto_20191101_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_address_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
