# Generated by Django 2.2.6 on 2019-11-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_auto_20191101_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
