# Generated by Django 2.2.7 on 2019-11-07 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=70)),
                ('item_badge', models.CharField(choices=[('none', 'NONE'), ('special', 'SPECIAL')], max_length=20)),
                ('item_category', models.CharField(choices=[('select a category', 'SELECT A CATEGORY'), ('antiques', 'ANTIQUES'), ('books', 'BOOKS'), ('cameras', 'CAMERAS'), ('collectibles', 'COLLECTIBLES'), ('dolls', 'DOLLS'), ('electronics', 'ELECTRONICS'), ('flatware', 'FLATWARE'), ('furniture', 'FURNITURE'), ('games', 'GAMES'), ('glassware', 'GLASSWARE'), ('household items', 'HOUSEHOLD ITEMS'), ('jewelry', 'JEWELRY'), ('knick knacks', 'KNICK KNACKS'), ('mens fashion', 'MENS FASHION'), ('miscellaneous', 'MISCELLANEOUS'), ('movies - dvd', 'MOVIES - DVD'), ('movies - vhs', 'MOVIES - VHS'), ('music - all', 'MUSIC - ALL'), ('music - cd', 'MUSIC - CD'), ('music - vinyl', 'MUSIC - VINYL'), ('novely items', 'NOVELTY ITEMS'), ('posters', 'POSTERS'), ('shoes', 'SHOES'), ('tools - all', 'TOOLS - ALL'), ('tools - hand tools', 'TOOLS - HAND TOOLS'), ('tools - power tools', 'TOOLS - POWER TOOLS'), ('tools - yard tools', 'TOOLS - YARD TOOLS'), ('womens fashion', 'WOMENS FASHION'), ('writing utensils', 'WRITING UTENSILS')], max_length=50)),
                ('photo_main', models.ImageField(upload_to='media/%Y%/m%/%d')),
                ('photo_front', models.ImageField(blank=True, upload_to='media/%Y%/m%/%d')),
                ('photo_back', models.ImageField(blank=True, upload_to='media/%Y%/m%/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('date_listed', models.DateTimeField(default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.Seller')),
            ],
        ),
    ]
