# Generated by Django 2.2.7 on 2019-11-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_listed',
            new_name='dateListed',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_published',
            new_name='isPublished',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_badge',
            new_name='itemBadge',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_category',
            new_name='itemCategory',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photo_back',
            new_name='photoBack',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photo_front',
            new_name='photoFront',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photo_main',
            new_name='photoMain',
        ),
    ]
