# Generated by Django 2.2.7 on 2019-11-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191107_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dateListed',
            new_name='date_listed',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='isPublished',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemBadge',
            new_name='item_badge',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemCategory',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photoBack',
            new_name='photo_back',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photoFront',
            new_name='photo_front',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photoMain',
            new_name='photo_main',
        ),
    ]
