# Generated by Django 2.2.6 on 2019-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191031_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_badge',
            field=models.CharField(choices=[('listed today', 'LISTED TODAY'), ('special', 'SPECIAL')], default='', max_length=20),
        ),
    ]
