# Generated by Django 2.2.6 on 2019-11-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20191101_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_badge',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
