# Generated by Django 2.2.6 on 2019-11-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191102_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_category',
            new_name='category',
        ),
    ]
