# Generated by Django 2.2.6 on 2019-11-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20191102_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('select a category', 'SELECT A CATEGORY'), ('antiques', 'ANTIQUES'), ('books', 'BOOKS'), ('cameras', 'CAMERAS'), ('collectibles', 'COLLECTIBLES'), ('dolls', 'DOLLS'), ('flatware', 'FLATWARE'), ('furniture', 'FURNITURE'), ('games', 'GAMES'), ('glassware', 'GLASSWARE'), ('household items', 'HOUSEHOLD ITEMS'), ('jewelry', 'JEWELRY'), ('knick knacks', 'KNICK KNACKS'), ('mens fashion', 'MENS FASHION'), ('miscellaneous', 'MISCELLANEOUS'), ('movies - dvd', 'MOVIES - DVD'), ('movies - vhs', 'MOVIES - VHS'), ('music - all', 'MUSIC - ALL'), ('music - cd', 'MUSIC - CD'), ('music - vinyl', 'MUSIC - VINYL'), ('novely items', 'NOVELTY ITEMS'), ('posters', 'POSTERS'), ('shoes', 'SHOES'), ('tools - all', 'TOOLS - ALL'), ('tools - hand tools', 'TOOLS - HAND TOOLS'), ('tools - power tools', 'TOOLS - POWER TOOLS'), ('tools - yard tools', 'TOOLS - YARD TOOLS'), ('womens fashion', 'WOMENS FASHION'), ('writing utensils', 'WRITING UTENSILS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_badge',
            field=models.CharField(choices=[('none', 'NONE'), ('special', 'SPECIAL')], max_length=20),
        ),
    ]
