# Generated by Django 2.2.6 on 2019-11-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20191103_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_list',
        ),
    ]
