# Generated by Django 2.2.6 on 2019-11-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20191104_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_list',
            new_name='category_list',
        ),
    ]
