# Generated by Django 2.2.6 on 2019-11-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20191104_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_list',
        ),
    ]
