# Generated by Django 2.2.6 on 2019-11-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20191104_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
