# Generated by Django 2.2.6 on 2019-11-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20191105_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=70),
        ),
    ]
