# Generated by Django 2.2.7 on 2019-11-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20191105_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_list',
            new_name='item_category',
        ),
    ]
